version: "3.8"

services:
  app:
    image: code.unianalysis.com:5050/unianalysis/elden/service
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    entrypoint:
      ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  queue:
    image: code.unianalysis.com:5050/unianalysis/elden/service
    env_file:
      - ../.env
    entrypoint:
      ["celery", "-A", "app", "worker", "--loglevel=INFO"]

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: elden
      MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: elden
