version: "3"

services:
  app:
    image: 
      searturky/punch-service
    restart: always
    # env_file:
    #   - ../.env
    ports:
      - 8000:8000
    depends_on:
      - "pgsql-15"

  web:
    image:
      searturky/punch-web
    restart: always
    ports:
      - 9528:80
    depends_on:
      - "app"

  pgsql-15:
    image: postgres:15-bullseye
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      TZ: "Asia/Shanghai"
      POSTGRES_USER: punch
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: punch
