version: "3.11.1"

services:
  pgsql-15:
    image: postgres:15-bullseye
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 27018:5432
    environment:
      TZ: "Asia/Shanghai"
      POSTGRES_USER: punch
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: punch